# Form implementation generated from reading ui file 'TranslateMate.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1096, 469)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(925, 385))
        MainWindow.setMaximumSize(QtCore.QSize(92500, 4000))
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("* {\n"
"   background-color: #b8b6b6;\n"
"   font: Fira Sans Condensed;     \n"
"}\n"
"QScrollBar {\n"
"    border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #f4f4f5;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #d0d0d0;\n"
"    min-height: 0px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: -10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height:  -10 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.translateLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.translateLabel.setGeometry(QtCore.QRect(10, 60, 40, 40))
        self.translateLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.translateLabel.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.translateLabel.setAutoFillBackground(False)
        self.translateLabel.setStyleSheet("#translateLabel {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#translateLabel:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.translateLabel.setText("")
        self.translateLabel.setPixmap(QtGui.QPixmap("img/translation.png"))
        self.translateLabel.setScaledContents(True)
        self.translateLabel.setObjectName("translateLabel")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 0, 1031, 451))
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainTranslate = QtWidgets.QWidget()
        self.MainTranslate.setObjectName("MainTranslate")
        self.inputBox = QtWidgets.QTextEdit(parent=self.MainTranslate)
        self.inputBox.setGeometry(QtCore.QRect(20, 50, 500, 380))
        self.inputBox.setStyleSheet("border: 1px solid black;\n"
"border-radius: 10px;\n"
"background: #f4f4f5;\n"
"font-size: 16px;\n"
"")
        self.inputBox.setObjectName("inputBox")
        self.translateBox = QtWidgets.QTextEdit(parent=self.MainTranslate)
        self.translateBox.setEnabled(True)
        self.translateBox.setGeometry(QtCore.QRect(530, 50, 500, 380))
        self.translateBox.setStyleSheet("border: 1px solid black;\n"
"border-radius: 10px;\n"
"background: #f4f4f5;\n"
"font-size: 16px;")
        self.translateBox.setReadOnly(True)
        self.translateBox.setObjectName("translateBox")
        self.copyTranslate = QtWidgets.QLabel(parent=self.MainTranslate)
        self.copyTranslate.setGeometry(QtCore.QRect(970, 380, 30, 30))
        self.copyTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.copyTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.copyTranslate.setAutoFillBackground(False)
        self.copyTranslate.setStyleSheet("#copyTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    opacity: 0.5;\n"
"    background: none;\n"
"    padding: 7px;\n"
"}\n"
"#copyTranslate:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.copyTranslate.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.copyTranslate.setText("")
        self.copyTranslate.setPixmap(QtGui.QPixmap("img/copy.png"))
        self.copyTranslate.setScaledContents(True)
        self.copyTranslate.setObjectName("copyTranslate")
        self.clearInput = QtWidgets.QLabel(parent=self.MainTranslate)
        self.clearInput.setGeometry(QtCore.QRect(470, 60, 30, 30))
        self.clearInput.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clearInput.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.clearInput.setAutoFillBackground(False)
        self.clearInput.setStyleSheet("#clearInput {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    background: none;\n"
"    opacity: 0.5;\n"
"    padding: 7px;\n"
"}\n"
"#clearInput:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.clearInput.setText("")
        self.clearInput.setPixmap(QtGui.QPixmap("img/close.png"))
        self.clearInput.setScaledContents(True)
        self.clearInput.setObjectName("clearInput")
        self.fromLang = QtWidgets.QComboBox(parent=self.MainTranslate)
        self.fromLang.setGeometry(QtCore.QRect(30, 10, 200, 30))
        self.fromLang.setStyleSheet("#fromLang {\n"
"    font: 11pt Fira Sans Condensed;     \n"
"    background-color: #2e2e2e;\n"
"    border-top: 0px solid #3e3e3e;\n"
"    border-left: 0px solid #3e3e3e;\n"
"    border-right: 0px solid #3e3e3e;\n"
"    border-bottom: 2px solid #3e3e3e;\n"
"    padding: 5%;\n"
"    max-height: 30px;\n"
"    min-width: 140px;\n"
"    color: white;\n"
"    selection-background-color: #5e5e5e;\n"
"    border-radius: 2px;\n"
"}\n"
"#fromLang:drop-down {\n"
"    border: none;\n"
"}\n"
"#fromLang:down-arrow {\n"
"    image: url(img/downButton.png);\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-width: 0px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#fromLang:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;\n"
"}")
        self.fromLang.setEditable(True)
        self.fromLang.setObjectName("fromLang")
        self.reverseTranslate = QtWidgets.QLabel(parent=self.MainTranslate)
        self.reverseTranslate.setGeometry(QtCore.QRect(510, 10, 30, 30))
        self.reverseTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reverseTranslate.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.reverseTranslate.setAutoFillBackground(False)
        self.reverseTranslate.setStyleSheet("#reverseTranslate {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#reverseTranslate:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.reverseTranslate.setText("")
        self.reverseTranslate.setPixmap(QtGui.QPixmap("img/reverseTranslate.png"))
        self.reverseTranslate.setScaledContents(True)
        self.reverseTranslate.setObjectName("reverseTranslate")
        self.toLang = QtWidgets.QComboBox(parent=self.MainTranslate)
        self.toLang.setGeometry(QtCore.QRect(820, 10, 200, 30))
        self.toLang.setStyleSheet("#toLang {\n"
"    font: 11pt Fira Sans Condensed;     \n"
"    background-color: #2e2e2e;\n"
"    border-top: 0px solid #3e3e3e;\n"
"    border-left: 0px solid #3e3e3e;\n"
"    border-right: 0px solid #3e3e3e;\n"
"    border-bottom: 2px solid #3e3e3e;\n"
"    padding: 5%;\n"
"    max-height: 30px;\n"
"    min-width: 140px;\n"
"    color: white;\n"
"    selection-background-color: #5e5e5e;\n"
"    border-radius: 2px;\n"
"}\n"
"#toLang:drop-down {\n"
"    border: none;\n"
"}\n"
"#toLang:down-arrow {\n"
"    image: url(img/downButton.png);\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-width: 0px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"#toLang:pressed {\n"
"    position: relative;\n"
"    top: 1px; left: 1px;\n"
"}")
        self.toLang.setEditable(True)
        self.toLang.setObjectName("toLang")
        self.saveTranslatedText = QtWidgets.QLabel(parent=self.MainTranslate)
        self.saveTranslatedText.setGeometry(QtCore.QRect(940, 380, 30, 30))
        self.saveTranslatedText.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.saveTranslatedText.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.saveTranslatedText.setAutoFillBackground(False)
        self.saveTranslatedText.setStyleSheet("#saveTranslatedText {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"    opacity: 0.5;\n"
"    background: none;\n"
"    padding: 7px;\n"
"}\n"
"#saveTranslatedText:hover  {\n"
"    opacity: 1;\n"
"    background: #dedddd;\n"
"}")
        self.saveTranslatedText.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.saveTranslatedText.setText("")
        self.saveTranslatedText.setPixmap(QtGui.QPixmap("img/saveTranslatedText.png"))
        self.saveTranslatedText.setScaledContents(True)
        self.saveTranslatedText.setObjectName("saveTranslatedText")
        self.stackedWidget.addWidget(self.MainTranslate)
        self.SaveTranslate = QtWidgets.QWidget()
        self.SaveTranslate.setObjectName("SaveTranslate")
        self.tableView = QtWidgets.QTableView(parent=self.SaveTranslate)
        self.tableView.setGeometry(QtCore.QRect(30, 30, 911, 381))
        self.tableView.setObjectName("tableView")
        self.stackedWidget.addWidget(self.SaveTranslate)
        self.saveTranslationWindow = QtWidgets.QLabel(parent=self.centralwidget)
        self.saveTranslationWindow.setGeometry(QtCore.QRect(10, 110, 40, 40))
        self.saveTranslationWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.saveTranslationWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.saveTranslationWindow.setAutoFillBackground(False)
        self.saveTranslationWindow.setStyleSheet("#saveTranslationWindow {\n"
"    background-repeat: no-repeat;\n"
"     border-radius:  5px;\n"
"}\n"
"#saveTranslationWindow:hover  {\n"
"    background:  #fff6f7;\n"
"}")
        self.saveTranslationWindow.setText("")
        self.saveTranslationWindow.setPixmap(QtGui.QPixmap("img/saveButton.png"))
        self.saveTranslationWindow.setScaledContents(True)
        self.saveTranslationWindow.setObjectName("saveTranslationWindow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 20))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuTranslate = QtWidgets.QMenu(parent=self.menubar)
        self.menuTranslate.setObjectName("menuTranslate")
        self.chooseTranslator = QtWidgets.QMenu(parent=self.menuTranslate)
        self.chooseTranslator.setObjectName("chooseTranslator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGoogleTranslator = QtGui.QAction(parent=MainWindow)
        self.actionGoogleTranslator.setCheckable(True)
        self.actionGoogleTranslator.setChecked(True)
        self.actionGoogleTranslator.setObjectName("actionGoogleTranslator")
        self.actionLeaveTheFormatting = QtGui.QAction(parent=MainWindow)
        self.actionLeaveTheFormatting.setCheckable(True)
        self.actionLeaveTheFormatting.setObjectName("actionLeaveTheFormatting")
        self.actionDeeplTranslator = QtGui.QAction(parent=MainWindow)
        self.actionDeeplTranslator.setCheckable(True)
        self.actionDeeplTranslator.setChecked(False)
        self.actionDeeplTranslator.setObjectName("actionDeeplTranslator")
        self.menuMenu.addAction(self.actionExit)
        self.chooseTranslator.addAction(self.actionDeeplTranslator)
        self.chooseTranslator.addAction(self.actionGoogleTranslator)
        self.menuTranslate.addAction(self.chooseTranslator.menuAction())
        self.menuTranslate.addAction(self.actionLeaveTheFormatting)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuTranslate.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translated mate"))
        self.translateLabel.setToolTip(_translate("MainWindow", "Translate text"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Input text"))
        self.copyTranslate.setToolTip(_translate("MainWindow", "Copy translate to clipboard"))
        self.clearInput.setToolTip(_translate("MainWindow", "Clear input and translated text"))
        self.reverseTranslate.setToolTip(_translate("MainWindow", "Reverse translate"))
        self.saveTranslatedText.setToolTip(_translate("MainWindow", "Save translated text"))
        self.saveTranslationWindow.setToolTip(_translate("MainWindow", "Save translation window"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuTranslate.setTitle(_translate("MainWindow", "Translate"))
        self.chooseTranslator.setTitle(_translate("MainWindow", "Translator"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionGoogleTranslator.setText(_translate("MainWindow", "Google"))
        self.actionLeaveTheFormatting.setText(_translate("MainWindow", "Leave the formatting"))
        self.actionDeeplTranslator.setText(_translate("MainWindow", "Deepl"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
